name: Python App Build template

on:
  push:
    branches: [ main ]
  pull_request:

env:
  COMMON_BUILD_REPO: '${{ secrets.COMMON_BUILD_REPO }}/CloudBroker/travis-scripts'
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GHE_TOKEN: ${{ secrets.GHE_TOKEN }}
  AFAAS_TOKEN: ${{ secrets.AFAAS_TOKEN }}
  AFAAS_USER: ${{ secrets.AFAAS_USER }}
  AFAAS_USER_NPM_TOKEN: ${{ secrets.AFAAS_USER_NPM_TOKEN }}
  AFAAS_DOCKER_REGISTRY: ${{ secrets.AFAAS_DOCKER_REGISTRY }}
  PYPI_USER: ${{ secrets.PYPI_USER }}
  PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  AFAAS_NPM_USER: ${{ secrets.AFAAS_NPM_USER }}
  AFAAS_NPM_TOKEN: ${{ secrets.AFAAS_NPM_TOKEN }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  AFAAS_URL: ${{ secrets.AFAAS_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.9]
    steps:
      - name: Initial step to pull Common Build tool script
        run: |
          ls -la
          pwd
          echo Start the curl command
          curl -s -u '${{ secrets.AFAAS_USER }}:${{ secrets.AFAAS_TOKEN }}' -X GET '${{ secrets.AFAAS_URL }}ibmcb-generic-local/BuildTools/get_build_tools.sh'
          ls -la
      - name: Set up Python 3.x environment on the runner 
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Log details
        run: | 
          pwd
          ls -la
          echo ${HOME}
