name: Python App Build template

on:
  push:
    branches: [ main ]
  pull_request:

env:
  COMMON_BUILD_REPO: '${{ secrets.COMMON_BUILD_REPO }}/CloudBroker/travis-scripts'
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GHE_TOKEN: ${{ secrets.GHE_TOKEN }}
  AFAAS_TOKEN: ${{ secrets.AFAAS_TOKEN }}
  AFAAS_USER: ${{ secrets.AFAAS_USER }}
  AFAAS_USER_NPM_TOKEN: ${{ secrets.AFAAS_USER_NPM_TOKEN }}
  AFAAS_DOCKER_REGISTRY: ${{ secrets.AFAAS_DOCKER_REGISTRY }}
  PYPI_USER: ${{ secrets.PYPI_USER }}
  PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  AFAAS_NPM_USER: ${{ secrets.AFAAS_NPM_USER }}
  AFAAS_NPM_TOKEN: ${{ secrets.AFAAS_NPM_TOKEN }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  AFAAS_URL: ${{ secrets.AFAAS_URL }}
  GITHUB_SERVER: 'GITHUB_SERVER'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: jfrog/setup-jfrog-cli@v1
        env: 
          JF_ARTIFACTORY_TOKEN: ${{ secrets.JF_ARTIFACTORY_TOKEN }}
      - run: |
          # Ping the server
          jfrog rt ping
          jfrog rt dl ibmcb-generic-local/BuildTools-testing/get_test_our.sh ${HOME}
          ls -la
          sh ${HOME}/get_test_our.sh
          ls -la
          cd travis-scripts
          ls -la

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.9]
    steps:
      - name: Initial step to pull Common Build tool script
        run: |
          ls -la
          pwd
          echo Start the curl command
          curl -s -u '${{ secrets.AFAAS_USER }}:${{ secrets.AFAAS_TOKEN }}' -X GET '${{ secrets.AFAAS_URL }}ibmcb-generic-local/BuildTools-testing/get_test_our.sh' | bash
          cd travis-scripts
          ls -la
          pwd
      - name: Set up Python 3.x environment on the runner 
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Log details
        run: | 
          pwd
          ls -la
          echo ${HOME}
